# Generated by Django 5.0.1 on 2025-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadoopMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('HDFS_CAPACITY', 'HDFS Capacity'), ('HDFS_USAGE', 'HDFS Usage'), ('MAPREDUCE_JOBS', 'MapReduce Jobs'), ('YARN_CONTAINERS', 'YARN Containers'), ('HIVE_QUERIES', 'Hive Queries')], max_length=50)),
                ('value', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cluster_name', models.CharField(default='default', max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
